# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: try to build
      run: |
        git clone https://ThatWhiteGuy364:${{ secrets.GH_TOKEN }}@github.com/ThatWhiteGuy364/test.git
        cd test
        python -m pip install -U Nuitka
        python -m nuitka --version
        python -m nuitka main.py
        git config --global user.email "zakwhite42364@gmail.com"
        git config --global user.name "ThatWhiteGuy364"
        git init
        git remote remove origin || true
        git add .
        git commit -m "Upload the files"
        git remote add origin https://ThatWhiteGuy364:${{ secrets.GH_TOKEN }}@github.com/ThatWhiteGuy364/test_upload.git
        branch="ci-upload-$(date +%s)"
        git checkout -b "$branch"
        git push -u origin "$branch"
        echo "Open a pull request from branch '$branch' to 'main'"
